export const DEFAULT_WEIGHTS=Object.freeze({knowledge:0.15,interpretation:0.20,production:0.35,transfer:0.30});
export const MASTERY_PROFILES=Object.freeze({
L1:{weightedMin:75,floors:{knowledge:85,interpretation:80,production:75,transfer:65}},
L2:{weightedMin:80,floors:{knowledge:85,interpretation:85,production:80,transfer:70}},
L3:{weightedMin:82,floors:{knowledge:85,interpretation:85,production:85,transfer:80}},
L4:{weightedMin:82,floors:{knowledge:90,interpretation:85,production:85,transfer:80,retention:80}},
L5:{weightedMin:84,floors:{knowledge:85,interpretation:85,production:90,transfer:85,retention:80},rubricMin:4},
Expert:{weightedMin:86,floors:{knowledge:85,interpretation:85,production:90,transfer:90,retention:80},rubricMin:4,capstoneMin:85,architectureReview:true}
});
const valid=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=100;
export function weightedScore(evidence,weights=DEFAULT_WEIGHTS){for(const key of Object.keys(weights))if(!valid(evidence[key]))throw new Error(`Invalid score for ${key}`);return Math.round(Object.entries(weights).reduce((s,[k,w])=>s+evidence[k]*w,0)*10)/10;}
export function evaluateMastery(level,evidence){const p=MASTERY_PROFILES[level];if(!p)throw new Error(`Unknown mastery level: ${level}`);const weighted=weightedScore(evidence),failures=[];for(const[d,f]of Object.entries(p.floors))if(!valid(evidence[d])||evidence[d]<f)failures.push({dimension:d,required:f,actual:evidence[d]??null});if(p.rubricMin!==undefined&&(typeof evidence.rubricMin!=='number'||evidence.rubricMin<p.rubricMin))failures.push({dimension:'rubricMin',required:p.rubricMin,actual:evidence.rubricMin??null});if(p.capstoneMin!==undefined&&(!valid(evidence.capstone)||evidence.capstone<p.capstoneMin))failures.push({dimension:'capstone',required:p.capstoneMin,actual:evidence.capstone??null});if(p.architectureReview&&evidence.architectureReview!==true)failures.push({dimension:'architectureReview',required:true,actual:evidence.architectureReview??false});if(weighted<p.weightedMin)failures.push({dimension:'weighted',required:p.weightedMin,actual:weighted});return{passed:failures.length===0,level,weighted,failures};}
export function adaptiveDepth(e){for(const k of['knowledge','interpretation','production','transfer'])if(!valid(e[k]))throw new Error('All adaptive-depth scores must be 0–100');if(e.knowledge>=90&&e.interpretation>=90&&e.production>=85&&e.transfer>=80)return'compression';if(e.knowledge>=85&&e.interpretation>=80&&e.production<75)return'guided-production';if(e.production>=85&&e.transfer<70)return'transfer-heavy';if(e.knowledge<70||e.interpretation<70)return'full-foundation';return'targeted-remediation';}
export function nextRetentionIntervalDays(history=[],criticality='normal'){if(history.length===0)return 1;if(history.at(-1)?.passed!==true)return 1;let streak=0;for(let i=history.length-1;i>=0&&history[i]?.passed===true;i--)streak++;const plan=criticality==='high'?[1,3,7,14,30,60]:[1,3,7,14,30];return plan[Math.min(streak,plan.length-1)];}
