import assert from 'node:assert/strict';
import {weightedScore,evaluateMastery,adaptiveDepth,nextRetentionIntervalDays} from '../mastery-engine.mjs';
assert.equal(weightedScore({knowledge:100,interpretation:100,production:100,transfer:100}),100);
assert.equal(evaluateMastery('L3',{knowledge:92,interpretation:90,production:88,transfer:84}).passed,true);
const weak=evaluateMastery('L3',{knowledge:96,interpretation:92,production:91,transfer:55});assert.equal(weak.passed,false);assert.ok(weak.failures.some(x=>x.dimension==='transfer'));
const l5=evaluateMastery('L5',{knowledge:90,interpretation:90,production:92,transfer:88,retention:85});assert.equal(l5.passed,false);assert.ok(l5.failures.some(x=>x.dimension==='rubricMin'));
assert.equal(adaptiveDepth({knowledge:95,interpretation:92,production:90,transfer:84}),'compression');
assert.equal(adaptiveDepth({knowledge:90,interpretation:85,production:60,transfer:70}),'guided-production');
assert.equal(adaptiveDepth({knowledge:82,interpretation:80,production:90,transfer:55}),'transfer-heavy');
assert.equal(adaptiveDepth({knowledge:60,interpretation:80,production:70,transfer:70}),'full-foundation');
assert.equal(nextRetentionIntervalDays([]),1);assert.equal(nextRetentionIntervalDays([{passed:true}]),3);assert.equal(nextRetentionIntervalDays([{passed:true},{passed:true},{passed:true}],'high'),14);assert.equal(nextRetentionIntervalDays([{passed:true},{passed:false}]),1);
console.log('mastery tests: PASS');
